services:
  react-app:
    build: .
    container_name: vite-react-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host

  react-tests:
    build: .
    container_name: vite-react-tests
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test